# Generated by Django 4.1.5 on 2023-05-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
