# Generated by Django 4.1.5 on 2023-05-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listing_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="time",),
    ]
